config/routes.rb
TestApp::Application.routes.draw do

  get 'categories'           => 'categories#index'
  get 'categories/:name'     => 'categories#show'
  get 'categories/:name/:id' => 'photos#show', :as => :photo_show
  
  get 'navigations' => 'navigations#index', :as => :navigations
  
  get 'events/:user_id/likes'      => 'navigations#show_likes',       :as => :event_likes
  get 'events/:user_id/comments'   => 'navigations#show_comments',    :as => :event_comments
  get 'events/:user_id/navigation' => 'navigations#show_navigations', :as => :event_navigations

  resources :photos
  resources :likes
  resources :comments

  devise_for :users
  

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name 
  has_many :photos
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :photo_id, :text
  
  validates :text, :length => {:minimum => 1, :maximum => 255}

  belongs_to :user, :counter_cache => true
  belongs_to :photo

  has_many :events, :as => :eventtable

  after_create :event_comment

  def event_comment
    self.events.create(:user_id => self.user.id, :eventtable_body => self.text)
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :eventtable_id, :eventtable_type, :eventtable_body, :user_id

  belongs_to :eventtable, :polymorphic => true
  belongs_to :user, :dependent => :destroy

  EVENT = %w{Navigation User Comment Like}
  validates :eventtable_type, :presence => true, :inclusion => {:in => EVENT}

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :user_id, :photo_id

  validates_uniqueness_of :user_id, :scope => :photo_id

  belongs_to :user, :counter_cache => true
  belongs_to :photo, :counter_cache => true

  has_many :events, :as => :eventtable

  after_create :event_like

  def event_like
    # self.events.create(:user_id => self.user.id)
    self.events.create(:user_id => 1)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :category_id, :address, :address_file_name

  belongs_to :category
  
  has_many :comments
  has_many :likes
  has_many :users, :through => :likes

  has_attached_file :address, :styles => { :small => "150x150", :thumb => "128x128>" , :large => "500x500"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates :email, :presence => true, :uniqueness => true

  has_many :events, :as => :eventtable
  has_many :comments, :dependent => :destroy
  has_many :likes
  has_many :photos, :through => :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter do
    Event.create(:eventtable_type => 'Navigation', :eventtable_body => request.env["REQUEST_URI"], :user_id => current_user.id) if current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    @name = params[:name]
    @photos = Category.find_by_name(params[:name]).photos.paginate(:page => params[:page]? params[:page] : 1, :per_page => 5)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_comment , :only => [:destroy,:update,:edit,:show]

  def index
    @comments = Comment.paginate(:page => params[:page], :per_page => 25).order("created_at")
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      redirect_to '/' << params[:comment][:return_path], notice: 'Comment was successfully created.'
    else
      render action: "new"
    end
  end

  def update

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def find_comment
    unless @comment = Comment.find_by_id(params[:id])
      redirect_to :root , :notice => "not found"
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @likes = Like.all
  end

  def show
    @like = Like.find(params[:id])
  end

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(params[:like])
    if @like.save
      format.html { redirect_to :back, notice: 'Like was successfully created.' }
    else
      format.html { render action: "new" }
    end
  end

end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  
  def index
    @users = User.all
  end

  def show_likes
    @user_photos = User.find(params[:user_id]).photos
  end
  
  def show_comments
    @user_comments = User.find(params[:user_id]).comments
  end

  def show_navigations
    @navigations = Event.find_all_by_user_id_and_eventtable_type(params[:user_id], :Navigation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!

  def index
    @photos = Photo.order('likes_count DESC').paginate(:page => params[:page]? params[:page] : 1, :per_page => 5)
  end

  def show
    @comments = Comment.new
    @photo = Photo.find(params[:id])
    @like = Like.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :count
    = f.number_field :count
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/get_category_id_photo.html.haml
%div= image_tag @photo.address.url(:small)
- if @photo.users.include?(current_user)
  %p 'like_it'
- else
  %p 'Click if like_it'

#comments
  = render 'comments'

app/views/categories/get_category_photos.html.haml
%h1= @name

#photos
  - @photos.each do |p|
    .photo= image_tag p.address.url(:thumb)
  
#paginate= will_paginate @photos

app/views/categories/index.html.haml
%h1 Categories

%table
  %tr
    %th Name
    / %th Count
    %th
    / %th
    / %th

  - @categories.each do |category|
    %tr
      %td= category.name
      / %td= category.count
      %td= link_to 'Show', 'categories/' << category.name
      / %td= link_to 'Edit', edit_category_path(category)
      / %td= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete

%br

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%h1= @name.capitalize

#photos
  - @photos.each do |p|
    .photo-box
      .photo
        = link_to image_tag( p.address.url(:thumb) ), photo_show_path(:name => @name, :id => p.id)
      .like
        - if p.users.include?(current_user)
          like_it
        - else 
          &nbsp;

/ .apple_pagination
.flickr_pagination
  .page_info= page_entries_info @photos
  = will_paginate @photos, :container => false

app/views/comments/_form.html.haml
= form_for @comment do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :photo_id
    = f.number_field :photo_id
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Comments

#comments
  = render :partial => 'photos/comment', :collection => @comments

/ .apple_pagination
.flickr_pagination
  .page_info= page_entries_info @comments
  = will_paginate @comments, :container => false

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @comment.text
%p
  %b User:
  = @comment.user_id
%p
  %b Photo:
  = @comment.photo_id

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title like_it?
    = stylesheet_link_tag "web-app-theme/base.css"
    = stylesheet_link_tag "web-app-theme/themes/drastic-dark/style.css"
    = stylesheet_link_tag :custom

    = javascript_include_tag :defaults, :cache => true
    = javascript_include_tag :application, :cache => true
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} like_it?
        #user-navigation
          %ul.wat-cf
            - if user_signed_in?
              %li
                %span.current_user
                  = t("web-app-theme.profile", :default => 'Signed in as: ' + current_user.email)
              %li
                = link_to( t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :method => :delete, :class => :logout)
            - else
              %li
                = link_to t("web-app-theme.logout", :default => "SignIn"), new_user_session_path, :class => :logout
              %li
                = link_to t("web-app-theme.logout", :default => "SignUp"), new_user_registration_path, :class => :logout
        #main-navigation
          %ul.wat-cf
            %li= link_to 'Categories', '/'
            %li= link_to 'Photos', photos_path
            %li= link_to 'Comments', comments_path
            %li= link_to 'Navigation', navigations_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} Web App.
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title like_it?
    = stylesheet_link_tag "web_app_theme"
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/likes/_form.html.haml
= form_for @like do |f|
  -if @like.errors.any?
    #error_explanation
      %h2= "#{pluralize(@like.errors.count, "error")} prohibited this like from being saved:"
      %ul
        - @like.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :photo_id
    = f.number_field :photo_id
  .actions
    = f.submit 'Save'

app/views/likes/edit.html.haml
%h1 Editing like

= render 'form'

= link_to 'Show', @like
\|
= link_to 'Back', likes_path

app/views/likes/index.html.haml
%h1 Listing likes

%table
  %tr
    %th User
    %th Photo
    %th
    %th
    %th

  - @likes.each do |like|
    %tr
      %td= like.user_id
      %td= like.photo_id
      %td= link_to 'Show', like
      %td= link_to 'Edit', edit_like_path(like)
      %td= link_to 'Destroy', like, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Like', new_like_path

app/views/likes/new.html.haml
%h1 New like

= render 'form'

= link_to 'Back', likes_path

app/views/likes/show.html.haml
%p#notice= notice

%p
  %b User:
  = @like.user_id
%p
  %b Photo:
  = @like.photo_id

= link_to 'Edit', edit_like_path(@like)
\|
= link_to 'Back', likes_path

app/views/navigations/index.html.haml
%h1 User navigation

%table
  %tr
    %th Email
    %th Navigation
    %th Last SignIn
    %th Last SignOut
    %th Likes
    %th Comments

  - @users.each do |user|
    %tr
      %td= user.email
      %td= link_to 'pre', event_navigations_path(:user_id => user.id)
      %td sign in
      %td sign out
      %td= link_to user.likes_count, event_likes_path(:user_id => user.id)
      %td= link_to user.comments_count, event_comments_path(:user_id => user.id)

app/views/navigations/show_comments.html.haml
= render :partial => 'photos/comment', :collection => @user_comments

app/views/navigations/show_likes.html.haml
%h1 User likes

#photos
  - @user_photos.each do |p|
    .photo-box
      .photo
        = image_tag(p.address.url(:thumb))
.clear

app/views/navigations/show_navigations.html.haml
- @navigations.each do |nav|
  .nav= nav.eventtable_body

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.haml

app/views/photos/_comment.html.haml
.comment
  %p= "#{comment.user.email} say - #{comment.text}"
  %p= "#{comment.created_at}"

app/views/photos/_comment_form.html.haml
#comment-form
  %h3 #Leave a comment
  = form_for @comments do |f|
    -if @comments.errors.any?
      #error_explanation
        %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
        %ul
          - @comments.errors.full_messages.each do |msg|
            %li= msg

    = f.hidden_field :photo_id, :value => @photo.id
    = f.hidden_field :user_id, :value => current_user.id
    = f.hidden_field :return_path, :value => [:categories, @photo.category.name, @photo.id].join('/')

    .field
      = f.label :text
      = f.text_field :text
    .actions
      = f.submit 'Add comment'

app/views/photos/_comments.html.haml
#comments
  %h3 #Comments
  = render :partial => "comment", :collection => @photo.comments
  %br

app/views/photos/_form.html.haml
= form_for @photo do |f|
  -if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :category_id
    = f.number_field :category_id
  .field
    = f.label :address
    = f.text_field :address
  .actions
    = f.submit 'Save'

app/views/photos/_like_form.html.haml
= form_for @like do |f|
  -if @like.errors.any?
    #error_explanation
      %h2= "#{pluralize(@like.errors.count, "error")} prohibited this like from being saved:"
      %ul
        - @like.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :photo_id, :value => @photo.id
  = f.hidden_field :user_id, :value => current_user.id
  .actions
    = f.submit 'Click if like_it!'

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1 Photos

#photos
  - @photos.each do |p|
    .photo-box
      .photo
        = link_to image_tag( p.address.url(:thumb) ), photo_show_path(:name => p.category.name, :id => p.id)
      .like
        = p.likes_count
        / - if p.users.include?(current_user)
        /   like_it
        / - else 
        /   &nbsp;

/ .apple_pagination
.flickr_pagination
  .page_info= page_entries_info @photos
  = will_paginate @photos, :container => false

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
#photo= image_tag @photo.address.url(:small)
#like-it
  - if @photo.users.include?(current_user)
    like_it
  - else
    = render 'like_form'
- if @photo.comments.count > 0
  = render 'comments'
= render 'comment_form'